version: "3.5"

networks:
  localhost:
    driver: bridge

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/mteressa/data/wordpress
      o: bind
      type: none
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/mteressa/data/mariadb
      o: bind
      type: none

services:
  nginx:
    depends_on:
      - wordpress
    container_name: nginx_cont
    build: ./nginx
    image: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - localhost
    restart: always
  mariadb:  
    container_name: mariadb_cont
    build: ./mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - localhost
    image: mariadb
    restart: always
  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress_cont
    build: ./wordpress
    image: wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - localhost
    restart: always
